id: P000676
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD105816
  title: བསླུ་བྲིད།
  author: ''
  volumes:
    f9ff795eb47543049513f23b13adf289:
      image_group_id: I1PD105818
      title: ''
      volume_number: 1
      total_pages: 394
