id: ICD8E0EE2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:27:17+00:00'
last_modified: '2022-06-07T12:38:15.879731+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD105816
  title: བསླུ་བྲིད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '8333':
      image_group_id: I1PD105818
      title: ''
      total_pages: 394
      order: 1
      base_file: 8333.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
